version: '3.8'

services:
  app:
    build: .
    container_name: casethread-app
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: tail -f /dev/null
    depends_on:
      - chromadb
    networks:
      - casethread-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: casethread-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    networks:
      - casethread-network

volumes:
  chroma_data:
    driver: local

networks:
  casethread-network:
    driver: bridge 