# Proposed Docker Compose Configuration for Multi-Agent System
# This shows what docker-compose.yml will look like after integration

version: '3.8'

services:
  # Keep the original service name for backward compatibility
  casethread-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casethread-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMADB_URL=http://chromadb:8000  # Internal Docker network URL
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    depends_on:
      - chromadb
    networks:
      - casethread-network

  chromadb:
    image: chromadb/chroma:latest
    container_name: casethread-chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    networks:
      - casethread-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  node_modules:
  chroma_data:
    driver: local

networks:
  casethread-network:
    driver: bridge 